# Generated by Django 3.2.19 on 2023-07-11 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inspections.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('upload_file', models.FileField(blank=True, max_length=255, null=True, upload_to=inspections.models.get_upload_path, verbose_name='Inspection Upload file')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_inspectionupload_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inspections.inspection')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_inspectionupload_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Inspection Upload',
            },
        ),
        migrations.DeleteModel(
            name='InspectionPicture',
        ),
    ]
