# Generated by Django 3.2.19 on 2023-06-25 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesorders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='signature_data',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='signature_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='SignatureId'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('signature_data', models.BinaryField(blank=True, null=True, verbose_name='Signature Image Data')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesorders_signature_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='salesorders.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesorders_signature_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Signature',
            },
        ),
    ]
