# Generated by Django 3.2.19 on 2023-06-25 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesorders', '0003_auto_20230625_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='salesorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sig', to='salesorders.salesorder'),
        ),
    ]
