# Generated by Django 3.2.19 on 2023-06-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorders', '0004_alter_signature_salesorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='part_type',
            new_name='vehicle_part',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='cust_reference_bool',
            new_name='cust_reference',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='discount_bool',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tint_package',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tint_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='addon_film',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tint_type',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tint_price',
        ),
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Order Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ala-carte'), (2, 'Continue Last Order'), (3, 'Package')], null=True, verbose_name='Order Mode'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_package',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Titan'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Platinum'), (6, 'Royal'), (7, 'Royal Plus'), (8, 'Royal Plus Safety')], null=True, verbose_name='Product Package'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addon',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Carbon Film - BK-50 2MIL'), (2, 'Carbon Film - BK-70 2MIL'), (3, 'Carbon Film - BK-80 2MIL'), (4, 'Carbon Film - BK-90 2MIL'), (5, 'Jasper 2MIL'), (6, 'Titan Black 2MIL'), (7, 'Ceramic 2MIL'), (8, 'Ceramic Black 2MIL'), (9, 'Ceramic Black DK 2MIL'), (10, 'PRO Nano 2MIL'), (11, 'Nano Shield 2MIL'), (12, 'Nano Shield DK 2MIL'), (13, 'Black Rainbow(Super Clear) 3MIL'), (14, 'Black Rainbow 3MIL'), (15, 'Black Rainbow DK 3MIL'), (16, 'Black Rainbow DR 3MIL')], null=True, verbose_name='Add-On'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Carbon Film - BK-50 2MIL'), (2, 'Carbon Film - BK-70 2MIL'), (3, 'Carbon Film - BK-80 2MIL'), (4, 'Carbon Film - BK-90 2MIL'), (5, 'Jasper 2MIL'), (6, 'Titan Black 2MIL'), (7, 'Ceramic 2MIL'), (8, 'Ceramic Black 2MIL'), (9, 'Ceramic Black DK 2MIL'), (10, 'PRO Nano 2MIL'), (11, 'Nano Shield 2MIL'), (12, 'Nano Shield DK 2MIL'), (13, 'Black Rainbow(Super Clear) 3MIL'), (14, 'Black Rainbow 3MIL'), (15, 'Black Rainbow DK 3MIL'), (16, 'Black Rainbow DR 3MIL')], null=True, verbose_name='Item Name'),
        ),
    ]
