# Generated by Django 3.2.19 on 2023-07-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorders', '0006_rename_claim_insurance_bool_orderitem_claim_insurance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',), 'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Sales Order'},
        ),
    ]
