# Generated by Django 3.2.19 on 2023-07-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorders', '0007_auto_20230702_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='to_accessories',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_package',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Titan'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Platinum'), (6, 'Royal'), (7, 'Royal Plus'), (8, 'Royal Plus Safety'), (9, 'Elemental'), (10, 'Eco Bonz 9H'), (11, 'Crystal Gloss 9H'), (12, 'Multi Quartz 9H'), (13, 'Avantgarde'), (14, 'Kosmos I'), (15, 'Kosmos II'), (16, 'Komsos III'), (17, 'Kleio'), (18, 'Morpheus'), (19, 'Matthias'), (20, 'Maximus')], null=True, verbose_name='Product Package'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='addon',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Door Visor'), (2, 'Coil Mat (B)'), (3, 'Coil Mat VIP (Red)'), (4, 'Coil Mat VIP (Black)'), (5, 'Coil Mat VIP (Grey)'), (6, 'Coil Mat 3D (Red)'), (7, 'Coil Mat 3D (Black)'), (8, 'Coil Mat 3D (Grey)'), (9, 'Sand Blasting'), (10, 'Carbon Film - BK-50 2MIL'), (11, 'Carbon Film - BK-70 2MIL'), (12, 'Carbon Film - BK-80 2MIL'), (13, 'Carbon Film - BK-90 2MIL'), (14, 'Jasper 2MIL'), (15, 'Titan Black 2MIL'), (16, 'Ceramic 2MIL'), (17, 'Ceramic Black 2MIL'), (18, 'Ceramic Black DK 2MIL'), (19, 'PRO Nano 2MIL'), (20, 'Nano Shield 2MIL'), (21, 'Nano Shield DK 2MIL'), (22, 'Black Rainbow (Super Clear) 3MIL'), (23, 'Black Rainbow 3MIL'), (24, 'Black Rainbow DK 3MIL'), (25, 'Black Rainbow DR 3MIL'), (26, 'Silica Coating')], null=True, verbose_name='Add-On'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Door Visor'), (2, 'Coil Mat (B)'), (3, 'Coil Mat VIP (Red)'), (4, 'Coil Mat VIP (Black)'), (5, 'Coil Mat VIP (Grey)'), (6, 'Coil Mat 3D (Red)'), (7, 'Coil Mat 3D (Black)'), (8, 'Coil Mat 3D (Grey)'), (9, 'Sand Blasting'), (10, 'Carbon Film - BK-50 2MIL'), (11, 'Carbon Film - BK-70 2MIL'), (12, 'Carbon Film - BK-80 2MIL'), (13, 'Carbon Film - BK-90 2MIL'), (14, 'Jasper 2MIL'), (15, 'Titan Black 2MIL'), (16, 'Ceramic 2MIL'), (17, 'Ceramic Black 2MIL'), (18, 'Ceramic Black DK 2MIL'), (19, 'PRO Nano 2MIL'), (20, 'Nano Shield 2MIL'), (21, 'Nano Shield DK 2MIL'), (22, 'Black Rainbow (Super Clear) 3MIL'), (23, 'Black Rainbow 3MIL'), (24, 'Black Rainbow DK 3MIL'), (25, 'Black Rainbow DR 3MIL'), (26, 'Silica Coating')], null=True, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='job_type',
            field=models.CharField(blank=True, choices=[(1, 'Do It Now'), (2, 'Pending'), (3, 'Install'), (4, 'Remove Old')], max_length=100, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vehicle_part',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Front Windscreen'), (2, 'Rear Windscreen'), (3, 'Interior'), (4, 'Headlight L'), (5, 'Headlight R'), (6, 'Canopy Window L'), (7, 'Canopy Window R'), (8, 'Side Window L1'), (9, 'Side Window L2'), (10, 'Side Window L3'), (11, 'Side Window R1'), (12, 'Side Window R2'), (13, 'Side Window R3'), (14, 'Sunroof 1'), (15, 'Sunroof 2'), (16, 'Sunvisor'), (17, 'Bodypaint'), (18, 'Front Part'), (19, 'Door L1'), (20, 'Door L2'), (21, 'Part L3'), (22, 'Door R1'), (23, 'Door R2'), (24, 'Door R3'), (25, 'Rooftop'), (26, 'Rear Part'), (27, 'Sport Rim'), (28, 'Windows'), (29, 'Door Cup L1'), (30, 'Door Cup L2'), (31, 'Door Cup R1'), (32, 'Door Cup R2'), (33, 'Door Edge L1'), (34, 'Door Edge L2'), (35, 'Door Edge R1'), (36, 'Door Edge R2'), (37, 'Fuel Cap'), (38, 'Front Fender L'), (39, 'Front Fender R'), (40, 'Front Door L'), (41, 'Front Door R'), (42, 'Front Foglamp'), (43, 'Front Grille'), (44, 'Pillar and Rear Fender L'), (45, 'Pillar and Rear Fender R'), (46, 'Rear Headlight L'), (47, 'Rear Headlight R'), (48, 'Skirting L'), (49, 'Skirting R'), (50, 'Rear Boot Edge'), (51, 'Rear Bumper'), (52, 'Rear Bumper Edge'), (53, 'Rear Bonnet'), (54, 'Rear Door L'), (55, 'Rear Door R'), (56, 'Side Mirror L'), (57, 'Side Mirror R'), (58, 'Spoiler'), (59, 'Side Step L1'), (60, 'Side Step L2'), (61, 'Side Step R1'), (62, 'Side Step R2'), (63, 'Gift')], null=True, verbose_name='Part'),
        ),
    ]
