# Generated by Django 3.2.19 on 2023-07-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorders', '0008_auto_20230704_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Accessories'), (2, 'Tint'), (3, 'Coating'), (4, 'PPF'), (5, 'Gift'), (6, 'MVP'), (7, 'Essential'), (8, 'Deluxe'), (9, 'Ultimate'), (10, 'XCA1'), (11, 'XCA2'), (12, 'XCA3'), (13, 'XCA5'), (14, 'Basic Coating Maintenance'), (15, 'Performance Coating Maintenance'), (16, 'Ultra Coat Maintenance')], null=True, verbose_name='Order Type'),
        ),
    ]
