# Generated by Django 3.2.19 on 2023-07-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorders', '0009_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='addon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Add-On'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vehicle_part',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Part'),
        ),
    ]
