# Generated by Django 3.2.19 on 2023-06-25 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='Category')),
                ('running_number', models.PositiveIntegerField(default=0, help_text='The current running number', null=True, verbose_name='Running Number')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numberings_numbering_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numberings_numbering_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Numbering',
                'verbose_name_plural': 'Numberings',
            },
        ),
    ]
