# Generated by Django 3.2.19 on 2023-06-25 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('car_plate', models.CharField(blank=True, default='', help_text='Required, Maximum of 50 Characters.', max_length=50, verbose_name='Car Plate No.')),
                ('car_brand', models.CharField(blank=True, default='', help_text='Required, Maximum of 255 Characters.', max_length=255, verbose_name='Car Brand.')),
                ('branch', models.CharField(blank=True, default='', help_text='Branch', max_length=255, verbose_name='Branch')),
                ('package', models.CharField(blank=True, default='', help_text='Required, Maximum of 150 Characters.', max_length=150, verbose_name='Car Plate No.')),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional, Add any extra notes related to the Loan.', verbose_name='Remarks')),
                ('number', models.CharField(blank=True, default='', max_length=25, verbose_name='Number')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_vehicle_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='partners.businesspartner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_vehicle_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('booking_date', models.DateTimeField(blank=True, help_text='Optional, time when customer do the appointment', null=True, verbose_name='Booking Date')),
                ('follow_up_date', models.DateTimeField(blank=True, help_text='Optional, time when customer do the follow up', null=True, verbose_name='Booking Date')),
                ('booking_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Booking Duration')),
                ('booking_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Appointment'), (2, 'Claim Appointment'), (3, 'Survey Appointment'), (4, 'Balance Appointment'), (5, 'Coating Maintenance Appointment')], null=True, verbose_name='Booking Type')),
                ('remark', models.CharField(blank=True, help_text='Optional', max_length=255, null=True, verbose_name='Remark')),
                ('number', models.CharField(blank=True, default='', max_length=25, verbose_name='Number')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_booking_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_booking_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('booking_date',),
            },
        ),
    ]
