# Generated by Django 3.2.19 on 2023-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bandar Puteri, Puchong (HQ)'), (2, 'Kota Damansara Branch'), (3, 'Shamelin, KL Branch'), (4, 'Kajang Branch'), (5, 'Balakong Branch')], default=None, help_text='Choose from the list', null=True, verbose_name='Branch'),
        ),
    ]
