# Generated by Django 3.2.19 on 2023-06-19 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Person'), (2, 'Group'), (3, 'Company')], default=1, help_text='Choose from the list.', null=True, verbose_name='Category')),
                ('profile_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Appointment'), (3, 'Verified'), (4, 'Banned'), (5, 'Blacklisted')], default=1, help_text='Required, Choose from the list', null=True, verbose_name='Profile Status')),
                ('name', models.CharField(blank=True, default='', help_text='Required, Maximum of 255 Characters.', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Please enter your Email Address.', max_length=255, null=True, verbose_name='Email')),
                ('ic_number', models.CharField(blank=True, default='', help_text='Maximum of 40 digits', max_length=40, verbose_name='IC Number')),
                ('passport_number', models.CharField(blank=True, default='', help_text='Maximum of 40 digits', max_length=40, verbose_name='Passport Number')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Maximum of 40 digits', max_length=40, verbose_name='Phone Number')),
                ('customer_from', models.CharField(blank=True, default='', help_text='Source of Customer', max_length=100, verbose_name='Customer From')),
                ('address', models.TextField(blank=True, default='', help_text='Optional, Add any extra notes related to the Loan.', verbose_name='Address')),
                ('language', models.CharField(blank=True, default='', help_text='Please select your language', max_length=100, verbose_name='Language')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrator'), (3, 'Telemarketer Lead'), (4, 'Telemarketer'), (5, 'Indoor Sales Lead'), (6, 'Indoor Sales'), (7, 'Technician Lead'), (8, 'Technician'), (2, 'Customer')], default=2, help_text='Required, Choose from the list', null=True, verbose_name='User Role')),
                ('number', models.CharField(blank=True, default='', max_length=25, verbose_name='Number')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_businesspartner_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_businesspartner_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
            },
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Required, PrimaryKey none-editable', primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this data is active or deleted', verbose_name='Active')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_hierarchy_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to='partners.businesspartner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_hierarchy_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
